### ISSUE TITLE
better-sqlite3.node was compiled against a different Node.js version

### ISSUE THREAD

**Issue by 413x1nkp** [FunnyDannyG/automaze#5]
[LOCAL] when try to run index.js:
```node
Uncaught Error Error: The module '\\?\C:\Users\alex\Documents\GitHub\automaze-fork\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (internal/modules/cjs/loader:1340:18)
    at Module.load (internal/modules/cjs/loader:1119:32)
    at Module._load (internal/modules/cjs/loader:960:12)
    at Module.require (internal/modules/cjs/loader:1143:19)
    at require (internal/modules/cjs/helpers:110:18)
    at bindings (c:\Users\alex\Documents\GitHub\automaze-fork\node_modules\bindings\bindings.js:112:48)
    at Database (c:\Users\alex\Documents\GitHub\automaze-fork\node_modules\better-sqlite3\lib\database.js:48:64)
    at Enmap (c:\Users\alex\Documents\GitHub\automaze-fork\node_modules\enmap\src\index.js:152:18)
    at <anonymous> (c:\Users\alex\Documents\GitHub\automaze-fork\index.js:26:17)
    at Module._compile (internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (internal/modules/cjs/loader:1310:10)
    at Module.load (internal/modules/cjs/loader:1119:32)
    at Module._load (internal/modules/cjs/loader:960:12)
    at executeUserEntryPoint (internal/modules/run_main:81:12)
    at <anonymous> (internal/main/run_main_module:23:47)
bindings.js:112
```

tried rebuilding via `npm rebuild better-sqlite3 --update-binary`, did not work. gave an error. removed `node.exe` from `node_modules\node\bin\node.exe`, and do `npm i`, didn't help.

next i did:

> 1. npm i -D electron-rebuild
> 2. Remove the node-modules folder, as well as the packages-lock.json file.
> 3. npm i
> 4. Run ./node_modules/.bin/electron-rebuild to rebuild everything

didn't help either.

**Comment by fungusdesu** [comment]
Backpedal to node v16.20.1, delete your package-lock.json and node_modules and `npm i` again
